version: "3.7"
services:
  app:
    build:
      args:
        user: backendsiw
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: backendsiw
    container_name: backendsiw-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www:delegated
    networks:
      - backendsiw
  mysql:
    image: mysql:8.0
    container_name: backendsiw-db
    restart: unless-stopped
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: backendsiw
      MYSQL_ROOT_PASSWORD: BackendSiwRoot
      MYSQL_PASSWORD: BackendSiw
      MYSQL_USER: fuad
      SERVICE_TAGS: dev
    networks:
      - backendsiw
  nginx:
    image: nginx:1.17-alpine
    container_name: backendsiw-nginx
    restart: unless-stopped
    ports:
      - 3000:80
    volumes:
      - ./:/var/www:delegated
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - backendsiw
  redis:
    image: redis:4.0.14
    container_name: backendsiw-redis
    # have password root
    command: redis-server --requirepass root
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - ./docker-compose/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - backendsiw
networks:
  backendsiw:
    driver: bridge
