version: "3.7"
services:
  app:
    build:
      args:
        user: niagahoster
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: niagahoster
    container_name: niagahoster-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www:delegated
    networks:
      - niagahoster
  mysql:
    image: mysql:5.7
    container_name: niagahoster-db
    restart: unless-stopped
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: niagahoster-backend
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: root
      SERVICE_TAGS: dev
    networks:
      - niagahoster
  nginx:
    image: nginx:1.17-alpine
    container_name: niagahoster-nginx
    restart: unless-stopped
    ports:
      - 3000:80
    volumes:
      - ./:/var/www:delegated
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - niagahoster
networks:
  niagahoster:
    driver: bridge
